import { Providers } from "@/modules/auth/components/wrapper/session-wrapper";
import "./globals.css";
import { ToasterProvider } from "./ToasterProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { ThemeProviderWrapper } from "@/shared/common/ThemeProviderWrapper";
import SubscriptionGuard from "@/modules/subscription/components/SubscriptionGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevCollab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <ThemeProviderWrapper> */}
        <Providers>
          <SubscriptionGuard>
            {children}
          </SubscriptionGuard>
        </Providers>
        <ToasterProvider />
        {/* </ThemeProviderWrapper> */}
      </body>
    </html>

  );
}
